# Generated by Django 3.2.7 on 2021-11-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='id_user',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
